### ISSUE TITLE
Line Detection Goals

### ISSUE THREAD

**Issue by ShaharMS** [ShaharMS/Vision#23]
Branch link: https://github.com/ShaharMS/Vision/tree/perf/faster-simple-line-detector

**Comment by Wither362** [comment]
Can I help?

**Comment by ShaharMS** [comment]
well, idk, im overhauling the entire thing and its gonna be very different thatn the original implementation.

i might split these changes into a branch of their own, and that should make it way easier for you to contribute. Ill update you

**Comment by Wither362** [comment]
> well, idk, im overhauling the entire thing and its gonna be very different thatn the original implementation.
> 
> i might split these changes into a branch of their own, and that should make it way easier for you to contribute. Ill update you

Ok, thanks

**Comment by ShaharMS** [comment]
If you're still interested, progress is made on the pref/faster-simple-line-detector branch. Feel free to improve the detection and fix some bugs ;)

**Comment by Wither362** [comment]
> If you're still interested, progress is made on the pref/faster-simple-line-detector branch. Feel free to improve the detection and fix some bugs ;)

Ok, I’ll see what I can do
