### ISSUE TITLE
Feature: Skew Images

### ISSUE THREAD

**Issue by ShaharMS** [ShaharMS/Vision#24]
This is a feature I find myself needing from time to time, whether to correct an image's "view point", or just place one picture on another. I think this is pretty important.

Progress:

 - [ ] `Vision.skew()`
 - [ ] `Vision.skewByExtension()` (?)
 - [ ] `image.stampSkewed()`

**Comment by Wither362** [comment]
I have some ideas for this to be done. And I have a solution for making rounded borders for images!

**Comment by ShaharMS** [comment]
Seems like this is solvable using matrices, but naming of these function may change because of that to adhere to standards (tilt instead of skew). Unsure as of now though

**Comment by ShaharMS** [comment]
This was solved in #41, closing this
