### ISSUE TITLE
Matrices

### ISSUE THREAD

**Issue by ShaharMS** [ShaharMS/Vision#41]
More of a log of matrix-relates features for 2.0.

When everything is completed (or ~dashed~ if cancelled), this will close.

 - [x] Matrix Implementation:
     - [x] Basic math & working operators
     - [x] Seamless type conversion
     - [x] Empty creation
     - [x] Generic filled creation
     - [x] Transformation matrix creation
- [x] Premade Matrices:
     - [x] Rotation
     - [x] Scaling
     - [x] Translation
     - [x] Shearing
     - [x] Reflection 
- [x] Image.hx Integration:
     - [x] Matrix application method
     - [x] Image rotation
     - [x] Image scaling
     - [x] Image perspective tilting

**Comment by ShaharMS** [comment]
almost there, just one problem - black gaps form when using some matrices:
![image](https://github.com/ShaharMS/Vision/assets/88977041/62849d81-e637-4889-a8d9-8c2185a3aec3)

Trying to resolve it right now, if you think you have a solution - feel free to suggest it :)

**Comment by Wither362** [comment]
> almost there, just one problem - black gaps form when using some matrices: ![image](https://user-images.githubusercontent.com/88977041/247618228-62849d81-e637-4889-a8d9-8c2185a3aec3.png)
> 
> Trying to resolve it right now, if you think you have a solution - feel free to suggest it :)

So… The problem is that there aren’t enough pixels to use in the gaps, right?

**Comment by ShaharMS** [comment]
Pretty much yeah...
I don't remember if I resolved it though, got busy with a bunch of other stuff...
Iirc I made a strange solution and then removed it because it was __very__ strange and had some side effects

**Comment by ShaharMS** [comment]
> > almost there, just one problem - black gaps form when using some matrices: ![image](https://user-images.githubusercontent.com/88977041/247618228-62849d81-e637-4889-a8d9-8c2185a3aec3.png)
> > Trying to resolve it right now, if you think you have a solution - feel free to suggest it :)
> 
> So… The problem is that there aren’t enough pixels to use in the gaps, right?

Okay, just checked stuff out - this was fixes using bilinear interpolation for the missing pixels, which actually looks like a pretty good solution. Moving on to perspective tilting, im also done with matrix application

**Comment by ShaharMS** [comment]
Update - just finished implementing perspective tilting, or, as its named in the library, warping.

I'm closing this. thanks @Wither362 for your help :)

**Comment by Wither362** [comment]
> Update - just finished implementing perspective tilting, or, as its named in the library, warping.
> 
> I'm closing this. thanks @Wither362 for your help :)

I really didn't do anything...
